config/routes.rb
Rails.application.routes.draw do
  #products routes
  root to: 'products#home'
  get 'home' => 'products#home'
  
  resources :products do  
    resources :reviews
  end

  #devise routes
  devise_for :users, controllers: { 
    sessions: 'devise/sessions',
    registrations: 'devise/registrations',
    # confirmations: 'users/confirmations',
    # omniauthcallbacks: 'users/omniauthcallbacks',
    # passwords: 'users/passwords',
    # unlocks: 'users/unlocks'
  }

  # devise_for :users, :path => '', :path_names => { 
  #   :sign_in => "login", 
  #   :sign_out => "logout", 
  #   :sign_up => "register" 
  # }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  before_save(:titleize_product)
  validates :name, :cost, :country_of_origin, presence: true
  validates :cost, numericality: true
 
  scope :made_in_usa, -> {(
    Product.where("country_of_origin>=?", "USA")
  )}

  scope :most_reviews, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(5)
  )}

  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
  private
    def titleize_product
      no_caps = ["a", "is", "you", "he", "she", "it", "we", "you", "me", "him", "her", "us", "my",  "his", "its", "our", "who",  "if", "how", "as"]
      result = []
      split_name = self.name.split(" ")
      split_name.each do |w|
        if no_caps.any? {|c| w == c }
          w = w
          result.push(w)
        else
        w = w.titleize
        result.push(w)
        end
      end  
      self.name = result.join(" ")
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, :content_body, :rating, presence: true
  validates :rating, numericality: true
  validates_length_of :content_body, in: 50..250
  validates_numericality_of :rating, greater_than: 0
  validates_numericality_of :rating, less_than_or_equal_to: 5
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :home, :show]

  def index
    @products = Product.all.order(:name).page(params[:page])
    render :index
  end

  def home 
    @products = Product.all 
    @most_recent_product = Product.three_most_recent   
    @most_reviewed_product = Product.most_reviews
    @products_made_in_usa = Product.made_in_usa
    render :home
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
 
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews.order(:updated_at).page(params[:page])
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end
end   

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    render :home
  end
  
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@product)
    else 
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy 
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

  private 
    def review_params
      params.require(:review).permit(:author, :content_body, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3> Please fix these errors: </h3>
  <ul> 
  <% object.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<br>
<%= form_for @product do |f| %>
  <input type="text" class ="form-control" name="product[name]" id="product_name" placeholder="Enter Product Name">
  <br>
  <input type="text" class ="form-control" name="product[cost]" id="product_cost" placeholder="Enter Product Cost">
  <br>
  <input type="text" class ="form-control" name="product[country_of_origin]" id="product_country_of_origin" placeholder="Enter Product Country of Origin">
  <br>
  <button type="submit" class="btn" name="commit" value="Create Product" data-disable-with="Create Product">Submit!</button>
<% end %>
<br>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>
<br>
<%= form_for [@product, @review] do |f| %>
  <input type="text" class ="form-control" name="review[author]" id="review_author" placeholder="Your Name">
  <br>
  <input type="text" class ="form-control" name="review[content_body]" id="review_content_body" rows="6" placeholder="Enter Review">
  <br>
  <input type="number" class ="form-control" name="review[rating]" id="review_rating" placeholder="Rate Product 1-5">
  <br>
  <button type="submit" class="btn" name="commit" value="Create review" data-disable-with="Create review">Submit!</button>
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeHouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <br>
  <div class = "top_links">
    <% if current_user %>
    <%= current_user.email %> | <%= link_to "SIGN OUT", destroy_user_session_path, method: :delete  %> 
    <% else %>
    <%= link_to "SIGN UP", new_user_registration_path %> | <%= link_to "SIGN IN", new_user_session_path %>
    <% end %>
  </div>
    <div class = "box">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1> EDIT PRODUCT</h1>

<%= render "layouts/product_form" %>

<footer><%= link_to "HOME PAGE", home_path %> || <%= link_to "PRODUCTS", products_path %></footer>

app/views/products/home.html.erb
<br>
<h1> Welcome to Maria's Coffee House!</h1>
<br>
<hr>

 <footer> <%= link_to "SEE ALL OF OUR CURRENT COFFEE", products_path%> </footer>

<h4>ABOUT US</h4>
<p>Reprehenderit anim elit enim ut. Non eu occaecat in mollit dolore. Pariatur adipisicing ea eiusmod dolor sunt Lorem non excepteur eiusmod quis dolore. Et dolore consequat ipsum laborum laborum id non nisi aliqua nostrud incididunt. Est et ullamco tempor do proident veniam. Laborum veniam qui eu ex magna ad voluptate velit adipisicing ad.</p>

<br>
<h4>NEWEST FEATURED PRODUCTS</h4>
<%# CODE FOR THREE MOST RECENTLY ADDED PRODUCTS %>

<% if @most_recent_product.any? %>
  <ul>
  <% @most_recent_product.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
  </ul>
<% else %> 
  <p>There are currently no products to display.</p>
<% end %>

<br>
<h4>OUR MOST POPULAR PRODUCT</h4>
<p>Ullamco esse sit fugiat ut voluptate adipisicing. Dolore sit nulla qui adipisicing. Proident tempor ex elit esse amet quis ex voluptate aliquip esse deserunt duis.</p>
<% if @most_reviewed_product.any? %>
  <ul>
  <% @most_reviewed_product.each do |product| %>
    <li><%= link_to product.name, product_path(product) %> has <%= product.reviews.count %> reviews!</li>
  <% end %>
  </ul>
<% else %> 
  <p>There are currently no products to display.</p>
<% end %>

<br>
<h4>OUR PRODUCTS MADE IN USA</h4>
<p>Ullamco esse sit fugiat ut voluptate adipisicing. Dolore sit nulla qui adipisicing. Proident tempor ex elit esse amet quis ex voluptate aliquip esse deserunt duis.</p>
<% if @products_made_in_usa.any? %>
  <ul>
  <% @products_made_in_usa.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
  </ul>
<% else %> 
  <p>Well, it doesn't look like the USA makes very good coffee...check back later!</p>
<% end %>

app/views/products/index.html.erb
<br>
<h1> MARIA'S COFFEE</h1>
<footer>
  <%= link_to "HOME PAGE", home_path %>  
   <% if current_user && current_user.admin %>  
    || <%= link_to "ADD PRODUCT", new_product_path %>
   <% end %>
</footer>
<br>
<hr>
<% if @products.any? %>
  <ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
  </ul>
<% else %> 
  <p>There are currently no products to display.</p>
<% end %>

<div class = "pagination">
  <%= paginate @products %>
</div>

app/views/products/landing_page.html.erb
<%# LANDING PAGE 
- information on company
- three most recently added products
- 'featured' product with the most reveiws %>


<h1> Welcome to Maria's Specialty Market!</h1>

<div class="header">
  <%= link_to "Check Out ALL of Our Other Products Here!", products_path%>
</div>

<h4>About Our Company</h4>
<p>Reprehenderit anim elit enim ut. Non eu occaecat in mollit dolore. Pariatur adipisicing ea eiusmod dolor sunt Lorem non excepteur eiusmod quis dolore. Et dolore consequat ipsum laborum laborum id non nisi aliqua nostrud incididunt. Est et ullamco tempor do proident veniam. Laborum veniam qui eu ex magna ad voluptate velit adipisicing ad.</p>

<h4>Here's our three most recently added products!</h4>
<%# CODE FOR THREE MOST RECENTLY ADDED PRODUCTS %>

<h4>Our MOST popular product!</h4>
<p>Ullamco esse sit fugiat ut voluptate adipisicing. Dolore sit nulla qui adipisicing. Proident tempor ex elit esse amet quis ex voluptate aliquip esse deserunt duis.</p>
<%# CODE FOR MOST POPULAR PRODUCT %>

app/views/products/new.html.erb
<h1> ADD NEW PRODUCT</h1>

<%= render "layouts/product_form" %>

<footer><%= link_to "HOME PAGE", home_path %> || <%= link_to "PRODUCTS", products_path %></footer>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<br>
<hr>
<div class="row">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-6">
        <h3>Origin: <%= @product.country_of_origin %> || Cost: $<%= @product.cost %>.00 </h3>
      </div>
      <div class="col">
        <div class = "header">
            <%= link_to "BACK", products_path%> 
            <% if current_user %>
               || <%= link_to "ADD REVIEW", new_product_review_path(@product)%>
            <% end %>
            <% if current_user && current_user.admin %>  
               || <%= link_to "ADD PRODUCT", new_product_path %> 
               || <%= link_to "EDIT PRODUCT", edit_product_path(@product) %>   
               || <%= link_to "DELETE PRODUCT", product_path(@product), method: :delete %>
            <% end %>
        </div>
      </div>
    </div>
    <br>


    <% if @product.reviews.any? %>
      <h4>PRODUCT REVIEWS:</h4>
      <hr>
        <% @product.reviews.each do |review| %>
          By: <%= review.author %> | Rating: <%= review.rating %> of 5
          <p><%= review.content_body %></p>
          <%if current_user && current_user.admin %>
            <p><%= link_to "edit", edit_product_review_path(@product, review)%><p>
          <% end %>
         <hr>
        <% end %>
        <div class = "pagination">
          <%= paginate @reviews %>
        </div>
    <% else %>
      <p>There are currently no reviews for this product!</p>
    <% end %>

    
    <footer> Would you like to leave a review of your own? Sign up <%= link_to "HERE", new_user_registration_path%></footer>
    <footer>| <%= link_to "HOME PAGE", home_path %> |</footer>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1> EDIT REVIEW </h1>
<%= render "layouts/errors", :object => @review %>
<br>
<%= form_for [@product, @review] do |f| %>
  <input type="text" class ="form-control" name="review[author]" id="review_author" placeholder="Your Name">
  <br>
  <input type="text" class ="form-control" name="review[content_body]" id="review_content_body" rows="6" placeholder="Enter Review">
  <br>
  <input type="number" class ="form-control" name="review[rating]" id="review_rating" placeholder="Rate Product 1-5">
  <br>
  <button type="submit" class="btn" name="commit" value="Create review" data-disable-with="Create review">Submit!</button>
<% end %>
<br>

<div class ="delete">
  <%= link_to "DELETE THIS REVIEW", product_review_path(@product, @review), :data => {:confirm => "Are you sure you'd like to delete this review?", :method => "delete"} %>
</div>

<footer><%= link_to "HOME PAGE", home_path %> || <%= link_to "PRODUCTS", products_path %></footer>

app/views/reviews/new.html.erb
<h1> ADD NEW REVIEW </h1>
<%= render "layouts/review_form" %>
<br>

<footer><%= link_to "HOME PAGE", home_path %> || <%= link_to "PRODUCTS", products_path %></footer>